### ISSUE TITLE
no-watch rule: not work

### ISSUE THREAD

**Issue by Rastraponovich** [effector/eslint-plugin#147]
Hello! 
Rule don't work in recommended preset and if we inline write config

```

extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react-hooks/recommended",
    "plugin:effector/recommended",
  ],
    parser: "@typescript-eslint/parser",
    parserOptions: { ecmaVersion: "latest", sourceType: "module" },
    plugins: ["react-refresh", "jsx-a11y", "prettier", "react", "effector"],
    rules: {
      "effector/no-watch": "error",
  },
...
]
```

<img width="952" alt="image" src="https://github.com/effector/eslint-plugin/assets/58354560/ab5c4508-55e1-4524-82b0-f5ea9a5f66b5">

 "eslint-plugin-effector": "^0.11.0",
"effector": "^22.8.6",
"eslint": "^8.38.0",

**Comment by igorkamyshev** [comment]
Hello! The reason is that in pure JS we do not have a way to check that is something is Event, so we use TS info for these checks. I suppose, in your setup, ESLint does not have access to types info. Check the corresponding issue for the more info — https://github.com/effector/eslint-plugin/issues/131

However, it will work with Store, because in Effector's ecosystem there is a specific convention what variable with $ is a Store.
